Адаптивная сетка для главной страницы
htmlacademy-adaptive/1446019-cat-energy-24 pull request #5
Opened 2021-12-04 19:25 UTC by snap9595

2021-12-04 19:40 UTC, snap9595 commented
у меня там хедер как то странно работает, и в firefoxе с декстопа на планшет, как то странно переходит

2021-12-04 23:54 UTC, Zakamsky requested changes
Записал видео ревью, необходимо пофиксить перестроение что бы страница не становилась шире экрана, и убрать огромные уши что бы не обижать пользователей ноутбуков и старых экранов планшетной версии.
Еще я бы посоветовал убрать max-width медиа, в текущем коде они создают больше повторов кода и путаницы чем экономят нам усилия.

2021-12-05 13:12 UTC, snap9595 commented
Все исправил, по поводу media выражения оказалось что писать внутри класса удобнее чем внизу. Может из за этого запутался с "ушами"

2021-12-05 16:38 UTC, Zakamsky approved these changes
Отличная работа над ошибками!

2021-12-05 16:38 UTC, merged